title: Nakal
subtitle: NAUGHTY STYLISH ITALIAN APPAREL
description: "Nakal is style for naughty dudes. Clean ass boys who dress to impress. Quality garments that are comfy to wear. Nakal pieces are well designed and it shows. A look that delivers. Cool and sober for all occasions."
keywords: apparel, pants, shirt, T-shirts, Italian, fashion
lang: en
version: 0.0.5
baseurl: ""
url: "https://nakal.co"
qr: show # 'show' or 'hide' put qr.svg in includes/defs.html call it: icn--qr

company:
  name: Nakal
  legal_name: Cv. Konsep #if overrides 'company.name' in footer
  email: info@nakal.co
  telephone: +62 361 271370
  fax: #
  address: Jl. Tukad Nyali 18x, Sanur, Bali
  maplink: https://goo.gl/maps/G23A2RhaQak
  country: Indonesia
  twitter: #
  facebook_page: #
  youtube: #
  instagram: #
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics: UA-124567145-1
  verification: google32e66f1a5601ec40

# Build settings
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty

collections:
  products:
    output: true
    permalink: /:title/
    layout: #
  pages:
    output: true
    permalink: /:title/
